r_pectoralis_major_controller:
  type: muscle_controllers/MuscleController
  name: r_pectoralis_major
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

r_deltoid_controller:
  type: muscle_controllers/MuscleController
  name: r_deltoid
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

r_triceps_brachii_controller:
  type: muscle_controllers/MuscleController
  name: r_triceps_brachii
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

r_biceps_brachii_controller:
  type: muscle_controllers/MuscleController
  name: r_biceps_brachii
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

r_brachialis_controller:
  type: muscle_controllers/MuscleController
  name: r_brachialis
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

r_brachioradialis_controller:
  type: muscle_controllers/MuscleController
  name: r_brachioradialis
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

r_flexor_carpi_ulnaris_controller:
  type: muscle_controllers/MuscleController
  name: r_flexor_carpi_ulnaris
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

r_extensor_digitorum_controller:
  type: muscle_controllers/MuscleController
  name: r_extensor_digitorum
  pid: {p: 1.0,  i: 1.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
